name: build-branches

on:
  push:
    branches:
      - '!main'
    paths-ignore:
      - '**.md'
      - 'website/**'
  pull_request:
    branches:
      - 'main'

jobs:
  build-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Gen cache keys
        run: |
          md5sum project/build.properties project/plugins.sbt build.sbt > $GITHUB_WORKSPACE/.sbt_cache_key
          cat $GITHUB_WORKSPACE/.sbt_cache_key
      - name: Check cache
        uses: actions/cache@v2.1.1
        with:
          key: sbt-${{ hashFiles('**/.sbt_cache_key') }}
          path: |
            ~/.ivy2
            ~/.sbt
            ~/.cache/coursier
      - name: Spin up Dynamo local
        run: docker-compose up -d
      - name: Test Dynamo connection
        run: |
          docker ps
          docker run --network container:dynamodb-local curlimages/curl:7.73.0 -v --retry 20 --retry-all-errors http://localhost:8000/
      - name: Run build and tests
        run:
          sbt ";+compile;+test;+it:test"
